<?php
/**
 * underscore.js template for the dialog for the cred_form shortcode.
 *
 * @since m2m
 */
?>
<script type="text/html" id="tmpl-cred-post-edit-form-template">
	<#
	data = _.extend( 
		data, 
		{
			attributes: {
				postSelection: {
					header: '<?php _e( 'Post selection', 'wp-cred' ); ?>',
					fields: {
						post: { 
							label: '<?php _e( 'Post to edit', 'wp-cred' ); ?>',
							type: 'post',
							defaultValue: 'current'
						} 
					}
				}
			}
		}
	);
	#>
	<# print( data.templates.dialog( data ) ); #>
</script>